### ISSUE TITLE
Tìm hiểu các thuật toán có liên quan

### ISSUE THREAD

**Issue by vohanhattan** [vohanhattan/RecommendationSystem#2]
- Euclidean algorithm: https://en.wikipedia.org/wiki/Euclidean_algorithm
- Pearson correlation: https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
- Cosine similarity: https://en.wikipedia.org/wiki/Cosine_similarity

**Comment by phunghx** [comment]
@vohanhattan các em post tài liệu đã tìm hiểu về thuật toán lên github
